<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>How to use the result type to handle errors in Swift 5? - The.Swift.Dev.</title>
    
    <meta name="description" content="From this tutorial you can learn how to utilize the do-try-catch syntax with the brand new result type to handle errors in Swift.">
    
    <meta property="og:title" content="How to use the result type to handle errors in Swift 5? - The.Swift.Dev.">
    <meta property="og:description" content="From this tutorial you can learn how to utilize the do-try-catch syntax with the brand new result type to handle errors in Swift.">
    <meta property="og:url" content="https://theswiftdev.com/how-to-use-the-result-type-to-handle-errors-in-swift/">
    <meta property="og:image" content="https://theswiftdev.com/images/assets/how-to-use-the-result-type-to-handle-errors-in-swift/cover.jpg">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@tiborbodecs">
    <meta name="twitter:creator" content="@tiborbodecs">
    <meta name="twitter:title" content="How to use the result type to handle errors in Swift 5? - The.Swift.Dev.">
    <meta name="twitter:description" content="From this tutorial you can learn how to utilize the do-try-catch syntax with the brand new result type to handle errors in Swift.">
    <meta name="twitter:image" content="https://theswiftdev.com/images/assets/how-to-use-the-result-type-to-handle-errors-in-swift/cover.jpg">
    
    <link rel="stylesheet" href="https://theswiftdev.com/css/style.css">
    <link rel="stylesheet" href="https://theswiftdev.com/css/syntax.css">
    
    <link rel="mask-icon" sizes="any" href="https://theswiftdev.com/images/icons/icon.svg">

    <link rel="shortcut icon" href="https://theswiftdev.com/images/icons/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="https://theswiftdev.com/images/icons/icon-320.png" type="image/png">
    
    <link rel="apple-touch-icon" href="https://theswiftdev.com/images/icons/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="57x57" href="https://theswiftdev.com/images/icons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="https://theswiftdev.com/images/icons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="https://theswiftdev.com/images/icons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="https://theswiftdev.com/images/icons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="https://theswiftdev.com/images/icons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="https://theswiftdev.com/images/icons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="https://theswiftdev.com/images/icons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="https://theswiftdev.com/images/icons/apple-touch-icon-180x180.png">
    
</head>

<body>
    <a href="https://theswiftdev.gumroad.com" class="ribbon">
        üìñ
    </a>
    <header id="page-header">
        <a href="https://theswiftdev.com/">
            <img 
                id="logo-image"
                src="https://theswiftdev.com/images/icons/icon-320.png"
                alt="Logo of The.Swift.Dev." 
                title="The.Swift.Dev."
            >
        </a>
    </header>
    
    <main>

        <article>
    <header>
        <section id="post-header" class="content-wrapper">
            <time datetime="2019/01/28">2019/01/28</time>
            <h1 class="title">How to use the result type to handle errors in Swift 5?</h1>
            <p class="excerpt">From this tutorial you can learn how to utilize the do-try-catch syntax with the brand new result type to handle errors in Swift.</p>
            <div class="meta">
                <span class="tag">Swift</span>
<span class="tag">Result</span>
            </div>
        </section>
        <section class="wrapper">
            <img id="post-image" src="https://theswiftdev.com/images/assets/how-to-use-the-result-type-to-handle-errors-in-swift/cover.jpg">
        </section>
    </header>

    <div id="contents">
        <section class="content-wrapper">
            <h2>Error handling basics in Swift</h2><p>The way of handling errors changed a lot since the first version of Swift. The first big milestone happened in <a href="https://www.netguru.com/blog/error-handling-swift" target="_blank">Swift 2</a>, where Apple completely revamped <a href="https://appventure.me/2015/06/19/swift-try-catch-asynchronous-closures/" target="_blank">error management</a>. Nowadays you can use the <code>do</code>, <code>try</code>, <code>catch</code>, <code>throw</code>, <code>throws</code>, <code>rethrows</code> keywords instead of dealing with nasty NSError pointers, so this was a warmly welcomed addition for the language. Now in Swift 5 we take another giant leap forward by introducing the <a href="https://www.hackingwithswift.com/articles/161/how-to-use-result-in-swift" target="_blank">Result type</a> as a built-in generic. First, let me show you all the best practices of error handling in the Swift programming language, next I'll show you some cool stuff by using results to deal with errors. üöß</p><h3>Optionals as error indicators</h3><p>For simple scenarios you can always use optional <a href="https://www.cocoawithlove.com/blog/2016/08/21/result-types-part-one.html" target="_blank">values</a>, to indicate that something bad happened. Also the <code>guard</code> statement is extremely helpful for situations like this.</p><pre><code class="language-swift"><span class="keyword">let</span> zeroValue = <span class="type">Int</span>(<span class="string">"0"</span>)! <span class="comment">// Int</span>
<span class="keyword">let</span> nilValue = <span class="type">Int</span>(<span class="string">"not a number"</span>) <span class="comment">// Int?</span>

<span class="keyword">guard let</span> number = <span class="type">Int</span>(<span class="string">"6"</span>) <span class="keyword">else</span> {
    <span class="call">fatalError</span>(<span class="string">"Ooops... this should always work, so we crash."</span>)
}
<span class="call">print</span>(number)</code></pre><p>If you don't really care about the underlying type of the error, this approach is fine, but sometimes things can get more complicated, so you might need some details about the problem. Anyway, you can always stop the execution by calling the <code>fatalError</code> method, but if you do so, well... your app will crash. üí•</p><p>There are also a couple other ways of stop execution process, but this could be a topic of a standalone post, so here is just a quick cheat sheet of available methods:</p><pre><code class="language-swift"><span class="call">precondition</span>(<span class="keyword">false</span>, <span class="string">"ouch"</span>)
<span class="call">preconditionFailure</span>(<span class="string">"ouch"</span>)
<span class="call">assert</span>(<span class="keyword">false</span>, <span class="string">"ouch"</span>)
<span class="call">assertionFailure</span>(<span class="string">"ouch"</span>)
<span class="call">fatalError</span>(<span class="string">"ouch"</span>)
<span class="call">exit</span>(-<span class="number">1</span>)</code></pre><p>The key difference between precondition and assertion is that assert will work only in debug builds, but precondition is evaluated always (even in release builds). Both methods will trigger a fatal error if the condition fails aka. is false. ‚ö†Ô∏è</p><h3>Throwing errors by using the Error protocol</h3><p>You can define your own error types by simply confirming to the built-in <code>Error</code> protocol. Usually most developers use an <code>enum</code> in order to define different reasons. You can also have a custom error message if you conform to the <code>LocalizedError</code> protocol. Now you're ready to throw custom errors, just use the throw keyword if you'd like to raise an error of your type, but if you do so in a function, you have to mark that function as a throwing function with the throws keywords. ü§Æ</p><pre><code class="language-swift"><span class="keyword">enum</span> DivisionError: <span class="type">Error</span> {
    <span class="keyword">case</span> zeroDivisor
}

<span class="keyword">extension</span> <span class="type">DivisionError</span>: <span class="type">LocalizedError</span> {
    <span class="keyword">public var</span> errorDescription: <span class="type">String</span>? {
        <span class="keyword">switch self</span> {
        <span class="keyword">case</span> .<span class="dotAccess">zeroDivisor</span>:
            <span class="keyword">return</span> <span class="string">"Division by zero is quite problematic. "</span> +
                   <span class="string">"(https://en.wikipedia.org/wiki/Division_by_zero)"</span>
        }
    }
}

<span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>) <span class="keyword">throws</span> -&gt; <span class="type">Int</span> {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="keyword">throw</span> <span class="type">DivisionError</span>.<span class="property">zeroDivisor</span>
    }
    <span class="keyword">return</span> x / y
}</code></pre><p>Great, so the divide function above can generate a custom error message. If the divisor is zero it'll throw the zeroDivision error case. Now imagine the following scenario: you are trying to read the contents of a file from the disk. There could be multiple types of errors related to permission or file existence, etc.</p><blockquote><p>Rethrowing Functions and Methods A function or method can be declared with the rethrows keyword to indicate that it throws an error only if one of it‚Äôs function parameters throws an error. These functions and methods are known as rethrowing functions and rethrowing methods. Rethrowing functions and methods must have at least one throwing function parameter.</p></blockquote><p>Ok, so a <a href="https://stackoverflow.com/questions/43305051/what-are-the-differences-between-throws-and-rethrows-in-swift" target="_blank">throwing</a> function can emit different error types, also it can propagate all the parameter errors, but how do we handle (or should I say: catch) these errors?</p><h3>The do-try-catch syntax</h3><p>You just simply have to try to execute do a throwing function. So don't trust the master, there is definitely room for trying out things! Bad joke, right? üòÖ</p><pre><code class="language-swift"><span class="keyword">do</span> {
    <span class="keyword">let</span> number = <span class="keyword">try</span> <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">0</span>)
    <span class="call">print</span>(number)
}
<span class="keyword">catch let</span> error <span class="keyword">as</span> <span class="type">DivisionError</span> {
    <span class="call">print</span>(<span class="string">"Division error handler block"</span>)
    <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
}
<span class="keyword">catch</span> {
    <span class="call">print</span>(<span class="string">"Generic error handler block"</span>)
    <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
}</code></pre><p>As you can see the syntax is pretty simple, you have a do block, where you can try to execute your throwing functions, if something goes wrong, you can handle the errors in different catch blocks. By default an error property is available inside every catch block, so you don't have to define one yourself by hand. You can however have catch blocks for specific error types by casting them using the <code>let error as MyType</code> sytnax right next to the catch keyword. So always try first, don't just do! ü§™</p><h3>Differences between try, try? and try!</h3><p>As we've seen before you can simply try to call a function that throws an error inside a do-catch block. If the function triggers some kind of error, you can put your <a href="https://andybargh.com/error-handling-in-swift/" target="_blank">error handling</a> logic inside the catch block. That's very simple &amp; straightforward.</p><p>Sometimes if you don't really care about the underlying error, you can simply convert your throwing function result into an optional by using try?. With this approach you'll get a nil result if something bad happens, otherwise you'll get back your regular value as it is expected. Here is the example from above by using try?:</p><pre><code class="language-swift"><span class="keyword">guard let</span> number = <span class="keyword">try</span>? <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">2</span>) <span class="keyword">else</span> {
    <span class="call">fatalError</span>(<span class="string">"This should work!"</span>)
}
<span class="call">print</span>(number) <span class="comment">// 5</span></code></pre><p>Another technique is to prevent error propagation by using try!, but you have to be extremely careful with this approach, because if the execution of the "tried function" fails, your application will simply crash. So use only if you're absolutely sure that the function won't throw an error. ‚ö†Ô∏è</p><pre><code class="language-swift"><span class="keyword">let</span> number = <span class="keyword">try</span>! <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">2</span>) <span class="comment">// This will work for sure!</span>
<span class="call">print</span>(number)</code></pre><p>There are a few places where it's accepted to use force try, but in most of the cases you should go on an alternate path with proper error handlers.</p><h3>Swift errors are not exceptions</h3><p>The Swift compiler always requires you to catch all thrown errors, so a situation of unhandled error will never occur. I'm not talking about empty catch blocks, but unhandled throwing functions, so you can't try without the do-catch companions. This is one key difference when comparing to exceptions. Also when an error is raised, the execution will just exit the current scope. Exceptions will usually unwind the stack, that can lead to memory leaks, but that's not the case with Swift errors. üëç</p><h2>Introducing the result type</h2><p>Swift 5 introduces a long-awaited generic result type. This means that error handling can be even more simple, without adding your own result implementation. Let me show you our previous divide function by using Result.</p><pre><code class="language-swift"><span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>) -&gt; <span class="type">Result</span>&lt;<span class="type">Int</span>, <span class="type">DivisionError</span>&gt; {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="keyword">return</span> .<span class="call">failure</span>(.<span class="dotAccess">zeroDivisor</span>)
    }
    <span class="keyword">return</span> .<span class="call">success</span>(x / y)
}

<span class="keyword">let</span> result = <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">2</span>)
<span class="keyword">switch</span> result {
<span class="keyword">case</span> .<span class="dotAccess">success</span>(<span class="keyword">let</span> number):
    <span class="call">print</span>(number)
<span class="keyword">case</span> .<span class="dotAccess">failure</span>(<span class="keyword">let</span> error):
    <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
}</code></pre><p>The result type in Swift is basically a generic enum with a .success and a .failure case. You can pass a generic value if your call succeeds or an Error if it fails.</p><p>One major advantage here is that the error given back by result is type safe. Throwing functions can throw any kind of errors, but here you can see from the implementation that a DivisionError is coming back if something bad happens. Another benefit is that you can use exhaustive switch blocks to "iterate through" all the possible error cases, even without a default case. So the compiler can keep you safe, e.g. if you are going to introduce a new error type inside your enum declaration.</p><p>So by using the Result type it's clear that we're getting back either result data or a strongly typed error. It's not possible to get both or neither of them, but is this better than using throwing functions? Well, let's get asynchrounous!</p><pre><code class="language-swift"><span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>, completion: ((() <span class="keyword">throws</span> -&gt; <span class="type">Int</span>) -&gt; <span class="type">Void</span>)) {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="call">completion</span> { <span class="keyword">throw</span> <span class="type">DivisionError</span>.<span class="property">zeroDivisor</span> }
        <span class="keyword">return</span>
    }
    <span class="call">completion</span> { <span class="keyword">return</span> x / y }
}

<span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">0</span>) { calculate <span class="keyword">in
    do</span> {
        <span class="keyword">let</span> number = <span class="keyword">try</span> <span class="call">calculate</span>()
        <span class="call">print</span>(number)
    }
    <span class="keyword">catch</span> {
        <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
    }
}</code></pre><p>Oh, my dear... an inner closure! A completion handler that accepts a throwing function, so we can propagate the error thrown to the outer handler? I'm out! ü§¨</p><p>Another option is that we eliminate the throwing error completely and use an optional as a result, but in this case we're back to square one. No underlying error type.</p><pre><code class="language-swift"><span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>, completion: (<span class="type">Int</span>?) -&gt; <span class="type">Void</span>) {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="keyword">return</span> <span class="call">completion</span>(<span class="keyword">nil</span>)
    }
    <span class="call">completion</span>(x / y)
}

<span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">0</span>) { result <span class="keyword">in
    guard let</span> number = result <span class="keyword">else</span> {
        <span class="call">fatalError</span>(<span class="string">"nil"</span>)
    }
    <span class="call">print</span>(number)
}</code></pre><p>Finally we're getting somewhere here, but this time let's add our error as a closure parameter as well. You should note that both parameters need to be optionals.</p><pre><code class="language-swift"><span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>, completion: (<span class="type">Int</span>?, <span class="type">Error</span>?) -&gt; <span class="type">Void</span>) {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="keyword">return</span> <span class="call">completion</span>(<span class="keyword">nil</span>, <span class="type">DivisionError</span>.<span class="property">zeroDivisor</span>)
    }
    <span class="call">completion</span>(x / y, <span class="keyword">nil</span>)
}

<span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">0</span>) { result, error <span class="keyword">in
    guard</span> error == <span class="keyword">nil else</span> {
        <span class="call">fatalError</span>(error!.localizedDescription)
    }
    <span class="keyword">guard let</span> number = result <span class="keyword">else</span> {
        <span class="call">fatalError</span>(<span class="string">"Empty result."</span>)
    }
    <span class="call">print</span>(number)
}</code></pre><p>Finally let's introduce result, so we can eliminate optionals from our previous code.</p><pre><code class="language-swift"><span class="keyword">func</span> divide(<span class="keyword">_</span> x: <span class="type">Int</span>, by y: <span class="type">Int</span>, completion: (<span class="type">Result</span>&lt;<span class="type">Int</span>, <span class="type">DivisionError</span>&gt;) -&gt; <span class="type">Void</span>) {
    <span class="keyword">guard</span> y != <span class="number">0</span> <span class="keyword">else</span> {
        <span class="keyword">return</span> <span class="call">completion</span>(.<span class="call">failure</span>(.<span class="dotAccess">zeroDivisor</span>))
    }
    <span class="call">completion</span>(.<span class="call">success</span>(x / y))
}

<span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">0</span>) { result <span class="keyword">in
    switch</span> result {
    <span class="keyword">case</span> .<span class="dotAccess">success</span>(<span class="keyword">let</span> number):
        <span class="call">print</span>(number)
    <span class="keyword">case</span> .<span class="dotAccess">failure</span>(<span class="keyword">let</span> error):
        <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
    }
}</code></pre><p>See? Strongly typed errors, without optionals. Handling errors in asynchronous function is way better by using the Result type. If you consider that most of the apps are doing some kind of networking, and the result is usually a JSON response, there you already have to work with optionals (response, data, error) plus you have a throwing JSONDecoder method... can't wait the new APIs! ‚ù§Ô∏è</p><h2>Working with the Result type in Swift 5</h2><p>We already know that the result type is basically an enum with a generic <code>.succes(T)</code> and a <code>.failure(Error)</code> cases, but there is more that I'd like to show you here. For example you can create a result type with a throwing function like this:</p><pre><code class="language-swift"><span class="keyword">let</span> result = <span class="type">Result</span> {
    <span class="keyword">return try</span> <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">2</span>)
}</code></pre><p>It is also possible to convert back the result value by invoking the get function.</p><pre><code class="language-swift"><span class="keyword">do</span> {
    <span class="keyword">let</span> number = <span class="keyword">try</span> result.<span class="call">get</span>()
    <span class="call">print</span>(number)
}
<span class="keyword">catch</span> {
    <span class="call">print</span>(error.<span class="property">localizedDescription</span>)
}</code></pre><p>Also there are <code>map</code>, <code>flatMap</code> for transforming success values plus you can also use the <code>mapError</code> or <code>flatMapError</code> methods if you'd like to transform failures. üòé</p><pre><code class="language-swift"><span class="comment">// Result&lt;Int, DivisionError&gt;</span>
<span class="keyword">let</span> result = <span class="call">divide</span>(<span class="number">10</span>, by: <span class="number">2</span>) 

<span class="comment">// Result&lt;Result&lt;Int, DivisionError&gt;, DivisionError&gt;</span>
<span class="keyword">let</span> mapSuccess = result.<span class="call">map</span> { <span class="call">divide</span>($0, by: <span class="number">2</span>) } 

<span class="comment">// Result&lt;Int, DivisionError&gt;</span>
<span class="keyword">let</span> flatMapSuccess = result.<span class="call">flatMap</span> { <span class="call">divide</span>($0, by: <span class="number">2</span>) } 
<span class="keyword">let</span> mapFailure = result.<span class="call">mapError</span> { 
    <span class="type">NSError</span>(domain: $0.<span class="property">localizedDescription</span>, code: <span class="number">0</span>, userInfo: <span class="keyword">nil</span>)
}

<span class="keyword">let</span> flatMapFailure = result.<span class="call">flatMapError</span> { 
    .<span class="call">failure</span>(<span class="type">NSError</span>(domain: $0.<span class="property">localizedDescription</span>, code: <span class="number">0</span>, userInfo: <span class="keyword">nil</span>)) 
}</code></pre><p>That's it about the Result type in Swift 5. As you can see it's extremely powerful to have a generic implementation built directly into the language. Now that we have result, I just wish for <a href="https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md" target="_blank">higher kinded types</a> or an <a href="https://gist.github.com/lattner/429b9070918248274f25b714dcfc7619" target="_blank">async / await</a> implementation. üëç</p>
        </section>
    </div>

</article>

<section id="share" class="content-wrapper">
    <p>
    <a
        href="https://x.com/intent/tweet?via=tiborbodecs&amp;hashtags=SwiftLang&amp;url=https://theswiftdev.com/how-to-use-the-result-type-to-handle-errors-in-swift/"
        target="_blank"
    >
        Share this article
    </a>
    <br> Thank you. üôè</p>
</section>

<section  class="wrapper">
    <div id="book">
        <div class="column left">
            <img src="https://theswiftdev.com/images/practical-server-side-swift-cover.png">
        </div>
        <div class="column right">
            <h3>Get the Practical Server Side Swift book</h3>
            <p>Swift on the server is an amazing new opportunity to build fast, safe and scalable backend apps. Write your very first web-based application by using your favorite programming language. Learn how to build a modular blog engine using the latest version of the Vapor 4 framework. This book will help you to design and create modern APIs that'll allow you to share code between the server side and iOS. Start becoming a full-stack Swift developer.</p>
            <a class="button" href="https://gumroad.com/l/practical-server-side-swift" target="_blank">Available on Gumroad</a>
        </div>
    </div>
</section>

<section id="author" class="content-wrapper">
    <img 
        id="author-image"
        src="https://theswiftdev.com/images/profiles/tiborbodecs.jpg"
        alt="Picture of Tibor B√∂decs" 
        title="Tibor B√∂decs"
    >
    <h3>Tibor B√∂decs</h3>
    <p class="title">CEO @ <a href="https://binarybirds.com/">Binary Birds</a></p>
    <p class="bio">Server side Swift enthusiast, book author, content creator.</p>

    <div class="links">
        <a href="mailto:mail.tib@gmail.com?subject=theswiftdev.com" target="_blank">Email</a> ¬∑ 
        <a href="https://x.com/tiborbodecs" target="_blank">X</a> ¬∑ 
        <a href="https://github.com/tib" target="_blank">GitHub</a> 
    </div>
</section>

        
    </main>

    <footer>
        <section class="content-wrapper">
            <img 
                src="https://theswiftdev.com/images/icons/icon-320.png"
                alt="Logo of The.Swift.Dev." 
                title="The.Swift.Dev."
            >

            <p>This site was generated using the <a href="https://swift.org/" target="_blank">Swift</a> programming language.</p>
            
            <p> 
                <a href="https://theswiftdev.com/">Home</a> ¬∑
                <a href="https://theswiftdev.com/rss.xml" target="_blank">RSS</a> ¬∑
                <a href="https://theswiftdev.com/sitemap.xml" target="_blank">Sitemap</a>
            </p>
            
            <p class="small">Created by Tibor B√∂decs &copy; 2015 - 2023.</p>
        </section>
    </footer>
</body>
</html>
